### ISSUE TITLE
[1.10.2] Magenta-Black Textures when installed Malisis Doors & Base Metals

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#102] opened 2016-09-11 16:56 UTC
My game is not crashing. but door textures are missing when plaing with MalisisDoors & BaseMetals

**Comment by jriwanek** [comment] 2016-09-27 07:39
Not a bug in Malisis Doors, This is actually a bug In base metals, I should have it fixed by the next release.

**Comment by 63502** [comment] 2016-10-09 05:37
Is this no texture bug only a thing with vanilla doors?
Because if so, I think this is happening to me too.

**Closed as completed** 2016-10-19 16:36 UTC
