### ISSUE TITLE
1.12 vanilla doors loose texture

### ISSUE THREAD

**Issue by tiarnia** [Ordinastie/MalisisDoors#164] opened 2017-07-30 13:56 UTC
7.0.3
all my vanilla doors have no texture now and the new doors are invisible half the time

**Comment by darthvader45** [comment] 2017-07-30 20:13
Happens to me with 6.1.3 for 1.11.2, as well.  Same exact bug.  Also, the door items have no texture.

Exact error in console: 
``[15:43:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[atm$a.class:?]
	at net.minecraft.block.BlockDoor.func_176208_a(BlockDoor.java:266) ~[amx.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1127) ~[alu.class:?]
	at net.malisis.doors.block.Door.removedByPlayer(Door.java:325) ~[Door.class:1.11.2-6.1.3]
	at atomicstryker.multimine.common.MultiMineServer.onClientSentPartialBlockPacket(MultiMineServer.java:160) ~[MultiMineServer.class:?]
	at atomicstryker.multimine.common.network.PartialBlockPacket$ScheduledCode.run(PartialBlockPacket.java:76) ~[PartialBlockPacket$ScheduledCode.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[15:43:35] [Client thread/INFO] [dsurround]: Muting sounds
[16:04:05] [Client thread/INFO] [dsurround]: Unmuting sounds
[16:04:14] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:15] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:15] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:16] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:17] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:17] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:17] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:20] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:20] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:20] [Server thread/WARN]: Fetching addPacket for removed entity
[16:04:20] [Server thread/WARN]: Fetching addPacket for removed entity
[16:06:02] [Server thread/WARN]: Fetching addPacket for removed entity
[16:06:02] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[atm$a.class:?]
	at net.minecraft.block.BlockDoor.func_176208_a(BlockDoor.java:266) ~[amx.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1127) ~[alu.class:?]
	at net.malisis.doors.block.Door.removedByPlayer(Door.java:325) ~[Door.class:1.11.2-6.1.3]
	at atomicstryker.multimine.common.MultiMineServer.onClientSentPartialBlockPacket(MultiMineServer.java:160) ~[MultiMineServer.class:?]
	at atomicstryker.multimine.common.network.PartialBlockPacket$ScheduledCode.run(PartialBlockPacket.java:76) ~[PartialBlockPacket$ScheduledCode.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more``

**Comment by Ordinastie** [comment] 2017-08-03 09:16
Fixed in latest update.

**Closed as completed by Ordinastie** 2017-08-03 09:16 UTC
