### ISSUE TITLE
[1.12] Door render invisible... sort of.

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#165] opened 2017-07-31 11:34 UTC
Version 1.12-7.0.3

Door render invisible, but not always. With double doors [one door will be invisible](https://pasteboard.co/GDtx8TU.png), unless you [look at it from an angle](https://pasteboard.co/GDtxAfd.png). (links go to screenshots of the problem)

**Comment by Lothrazar** [comment] 2017-08-01 18:05
This also happens for me. fence gates are constantly going invisible. Makes the mod unusable to be honest.


![malisis doors but](https://user-images.githubusercontent.com/621529/28839671-41bf9466-76a9-11e7-9ee4-9f06109ceac6.png)

**Comment by brisingraerowing** [comment] 2017-08-01 22:49
This is also happening in 1.11.2.

I also get a rather weird, hard-light style rendering sometimes (which actually looks kind of cool. Maybe an idea for a future door style?)

![2017-07-30_23 34 56](https://user-images.githubusercontent.com/250409/28850340-0242353c-76ea-11e7-99b0-e13ccfb17292.png)

**Comment by MokahTGS** [comment] 2017-08-02 20:00
Yup, was just about to make an issue for this.  We are on 1.12 and get the invisible door, the semi-transparent doors and this new blocky texture version as well:

https://www.dropbox.com/s/jd1ruiqg8wcg5qd/2017-08-02_11.53.40.png?dl=0

https://www.dropbox.com/s/jd1ruiqg8wcg5qd/2017-08-02_11.53.40.png?dl=0

**Comment by Ordinastie** [comment] 2017-08-02 20:04
@MokahTGS Shoji Doors are translucent by design. I don't see anything wrong in your screens. Maybe it's because you posted the same twice ?

**Comment by MokahTGS** [comment] 2017-08-02 23:10
https://www.dropbox.com/s/fju2op4zh24o6xd/2017-08-02_11.53.34.png?dl=0

Sorry I wasn't clear.  We are having the issue on all doors just like everyone else as well as the texture issue above.

**Comment by Ordinastie** [comment] 2017-08-03 09:15
Fixed in latest update.

**Closed as completed by Ordinastie** 2017-08-03 09:15 UTC
