### ISSUE TITLE
Texture bug, without resource pack

### ISSUE THREAD

**Issue by NicosaurusRex99** [Ordinastie/MalisisDoors#155] opened 2017-05-23 07:12 UTC
Issue,
all doors show alot of textures on the top section rather than the top section of the door

Versions
Minecraft: 1.11.2
Forge: 13.20.0.2304
MalisisCore: 5.1.1
MalisisDoors: Boo 6.1.0

Link to video
https://youtu.be/QucAFkCrhNs

**Comment by TheLimePixel** [comment] 2017-05-24 17:41
This bug has been going on for 2 months now. I'd greatly appreciate it if it's fixed.

**Comment by Ordinastie** [comment] 2017-05-25 13:39
Most likely a duplicate of #154 .

**Closed as completed by Ordinastie** 2017-05-25 13:39 UTC

**Comment by NicosaurusRex99** [comment] 2017-05-26 03:33
@Ordinastie there was no resource pack involved though

**Comment by FiveEYZ** [comment] 2017-05-28 23:43
setting `B:config.modifyVanillaDoors=` to false fixes this

bye bye animated vanilla doors

**Comment by NicosaurusRex99** [comment] 2017-05-29 10:20
y no mid point, keep animation remove buggy texture @FiveEYZ
