### ISSUE TITLE
Hi-Tech door vanishes

### ISSUE THREAD

**Issue by syntaxer** [Ordinastie/MalisisDoors#152] opened 2017-05-16 23:08 UTC
Hi-Tech door turns invisible after a while.
![2017-05-17_01 52 31](https://cloud.githubusercontent.com/assets/5112222/26131625/b8da00fa-3aa3-11e7-9d7e-df508d1ea928.png)

Here you can barely see the outline when it turns invisible:
![2017-05-17_01 52 22](https://cloud.githubusercontent.com/assets/5112222/26131631/c3c6d9ac-3aa3-11e7-90df-0ae302cc2218.png)

If you right-click on it to open it will turn visible again.
It sometimes turns visible by it's own and replays the door closing animation even though the door was closed.

Minecraft 1.10.2
Forge 1.10.2-12.18.3.2254
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar

## **EDIT:**
I found the culprit to be the Aroma Mining dimension.
I'm using the latest Aroma mods for 1.10.2:
Aroma1997Core-1.9.4-1.1.1.2.jar
Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar

I've created a new creative world and added a Hi-Tech door and an Aroma portal. There was no issue until I traveled through the portal then came back and the door started to get invisible.

I've also noticed that a ghost version of the door is present in the Aroma dimension, but you can't interact with it.
![2017-05-17_03 41 42](https://cloud.githubusercontent.com/assets/5112222/26134011/390d96be-3ab4-11e7-90b7-3962f3ab16bb.png)

By disabling the 2 Aroma mods it fixes the invisible door, but I don't want to disable them as I have an automated mining operation set up in there.

**Comment by syntaxer** [comment] 2017-05-17 00:29
I found the culprit. The 2 Aroma mods are causing it.

I've created a new creative world and added a Hi-Tech door and an Aroma portal. There was no issue until I traveled through the portal then came back and the door started to get invisible.

By disabling the 2 Aroma mods it fixes the invisible door.
Now I don't know if the issue is in Malisis Doors or in the Aroma mods, but I don't want to disable them as I have an automated mining operation set up in there.

Can you please take a look?

**Comment by Ordinastie** [comment] 2017-05-25 13:40
Duplicate of #151.

**Closed as completed by Ordinastie** 2017-05-25 13:40 UTC
